version: '3'
services:
  client:
    image: 'omriasu/multi-client-upgrade'
    mem_limit: 128m
    hostname: client
  server:
    image: 'omriasu/multi-server-upgrade'
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: 'omriasu/multi-worker-upgrade'
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: 'omriasu/multi-nginx-upgrade'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
