name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t omriasu/react-test-up -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true omriasu/react-test-up npm test

      - run: docker build -t omriasu/multi-client-upgrade ./client
      - run: docker build -t omriasu/multi-nginx-upgrade ./nginx
      - run: docker build -t omriasu/multi-server-upgrade ./server
      - run: docker build -t omriasu/multi-worker-upgrade ./worker

      - run: docker push omriasu/multi-client-upgrade
      - run: docker push omriasu/multi-nginx-upgrade
      - run: docker push omriasu/multi-server-upgrade
      - run: docker push omriasu/multi-worker-upgrade

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker-upgrade
          environment_name: Multi-docker-upgrade-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-084375559775
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
